# Generated by Django 3.1.7 on 2021-09-15 05:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя игрока')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта игрока')),
                ('is_sponsor', models.BooleanField(default=False, verbose_name='Огранизатор?')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration', models.TextField(max_length=200, verbose_name='Описание желаемого подарка')),
                ('selected', models.BooleanField(default=False, verbose_name='Подарок выбан?')),
                ('grantor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='wish_grantor', to='main.player')),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_wisher', to='main.player')),
            ],
            options={
                'verbose_name': 'Желанный подарок',
                'verbose_name_plural': 'Желанные порарки',
            },
        ),
        migrations.CreateModel(
            name='Hate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration', models.TextField(max_length=200, verbose_name='Описание НЕжелательного подарка')),
                ('hater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hate_hater', to='main.player')),
            ],
            options={
                'verbose_name': 'НЕжеланный подарок',
                'verbose_name_plural': 'Нежеланные порарки',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('is_price_limit', models.BooleanField(default=False, verbose_name='Ограничиваем цену подарка?')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
